prefixes:
  - 'default*'
  - 'defaultcbot '

commandSpyPrefixes:
  - '/defaultcbot '

consolePrefixes:
  normalCommandsPrefix: '.'
  consoleServerPrefix: '/'

reconnectDelay: 7000

keys:
  normalKey: 'normal hash key here'
  ownerKey: 'OwnerHash™ key here'
core:
  layers: 3
  refillInterval: 60000
  # PLEASE give valid JSON component here else the core don't refill at all
  customName: '[{"text":"ChomeNS ","color":"yellow"},{"text":"Core","color":"green"},{"text":"™","color":"gold"}]'
selfCare:
  checkInterval: 1000,

  # vanilla
  op: true
  gamemode: true
  endCredits: true

  # essentials
  vanish: true
  nickname: true
  socialspy: true
  mute: true

  # extras
  cspy: true
  prefix: true
bots:
  # username and kaboom are optional.
  # for username if it doesn't exist it will default to random username
  # for kaboom it will just default to `false`
  - host: 'localhost'
    port: 25565
    username: 'ChomeNS_Bot'
    kaboom: false
