prefixes:
  - 'default*'
  - 'defaultcbot '

commandSpyPrefixes:
  - '/defaultcbot '

consolePrefixes:
  normalCommandsPrefix: '.'
  consoleServerPrefix: '/'

reconnectDelay: 7000

discord:
  prefix: 'default!'
  token: 'token here'
  trustedRoleName: 'Trusted'
  adminRoleName: 'Admin' # NOTE: admin will be able to access servereval..
  servers:
    localhost:25565: 'channel id'

ownerName: 'chayapak' # currently this is only used in the creator command and the console

trusted:
  - 'player name'

keys:
  normalKey: 'normal hash key here'
  ownerKey: 'OwnerHash™ key here'

weatherApiKey: 'key here' # weatherapi.com key

core:
  layers: 3
  refillInterval: 60000
  # PLEASE give valid JSON component here else the core don't refill at all
  customName: '[{"text":"ChomeNS ","color":"yellow"},{"text":"Core","color":"green"},{"text":"™","color":"gold"}]'
selfCare:
  checkInterval: 1000

  # vanilla
  op: true
  gamemode: true
  endCredits: true

  # essentials
  vanish: true
  nickname: true
  socialspy: true
  mute: true

  # commandspy
  cspy: true

  # icu (icontrolUwU)
  icu:
    enabled: true
    positionPacketsPerSecond: 10 # 10 seems to be a best number for me

  # extras
  prefix: true
  username: true # do NOT set this to false unless you know what you are doing
bots:
  # username, kaboom, useCore, useChat and hasEssentials are optional.

  # for username if it doesn't exist it will default to random username
  # for kaboom it will just default to `false`
  # for serverName name it whatever you like, it will be used as server name in trusted broadcast
  # for useCore it just sends the command using chat instead of using core. recommended to enable useChat too when this is enabled
  # for useChat when the bot sends output (tellraw) it will chat instead of using the core to run tellraw
  # for hasEssentials it is self-explanatory. if the server has essentials plugin just set it to true

  - host: 'localhost'
    port: 25565
    username: 'ChomeNS_Bot'
    kaboom: false
    serverName: 'Localhost'
    useCore: true
    useChat: false
    hasEssentials: false
