# Config file for ChomeNS Bot

prefixes:
  - 'default*'
  - 'defaultcbot '

commandSpyPrefixes:
  - '/defaultcbot '

consoleCommandPrefix: '.'

internetCheck:
  enabled: true
  address: 'https://sus.red'

# how backup works is that it checks for the address every 1 minute,
# if the address is reachable it will not start the bot
# if the address is not reachable then it will start the bot
#
# if the bot has already been started and the address is back up it
# will stop the bot (using System.exit(1))
backup:
  enabled: false
  address: 'https://fard.sex/check'

discord:
  enabled: false
  prefix: 'default!'
  token: 'token here'
  trustedRoleName: 'Trusted'
  adminRoleName: 'Admin' # NOTE: admin will be able to access servereval..
  statusMessage: 'Say Gex'
  inviteLink: 'https://discord.gg/xdgCkUyaA4'
  servers:
    localhost:25565: 'channel id'

music:
  URLRatelimit:
    seconds: 15
    limit: 7

colorPalette:
  primary: 'yellow'
  secondary: 'gold'
  defaultColor: 'white' # ig java has the `default` keyword so i need to use defaultColor
  username: 'gold'
  uuid: 'aqua'
  string: 'aqua'
  number: 'gold'
  ownerName: 'green'

# currently this is only used in the console
ownerNames:
  # don't leave this array blank or it can cause errors
  - 'chayapak'

ownerAuthentication:
  enabled: false
  key: ''
  timeout: 6000

trusted:
  - 'player name'

keys:
  normalKey: 'normal hash key here'
  ownerKey: 'OwnerHash™ key here'

weatherApiKey: 'key here' # weatherapi.com key

core:
  start:
    x: 0
    y: 0
    z: 0
  end:
    x: 15
    y: 2
    z: 15
  refillInterval: 300000 # (60 * 5) * 1000 (5 minutes)
  # PLEASE give valid JSON component here else the core don't refill at all
  customName: '[{"text":"ChomeNS ","color":"yellow"},{"text":"Core","color":"green"},{"text":"™","color":"gold"}]'

selfCare:
  delay: 225 # NOTE: self care does NOT use chat queue

  # vanilla
  op: true
  gamemode: true
  endCredits: true

  # essentials
  vanish: true
  nickname: true
  socialspy: true
  mute: true

  # commandspy
  cspy: true

  # icu (icontrolUwU)
  icu:
    enabled: true
    positionPacketsPerSecond: 10 # 10 seems to be the best number for me

  # extras
  prefix:
    enabled: true
    prefix: '&8[&eChomeNS Bot&8]'
  username: true # MIGHT cause problem(s) if set to false (not tested,.,.)

eval:
  address: 'ws://localhost:3069'

bots:
  # username - optional, if not specified it will just use a random username
  # creayun - defaults to false
  # serverName - name it whatever you like, it will be used as server name in trusted broadcast and in console
  # useCore - if enabled it just sends the command using chat instead of using core. recommended to enable useChat too when this is enabled
  # useChat - when the bot tellraws it will chat instead of using the core to run tellraw
  # removeNamespaces - when the bot sends a command it will remove like `minecraft:` for example if set to true
  # coreRateLimit - will ignore commands if reached the ratelimit

  - host: 'localhost'
    port: 25565
    username: 'ChomeNS_Bot'
    creayun: false
    serverName: 'Localhost'
    useCore: true
    useChat: false
    reconnectDelay: 2000
    removeNamespaces: false
    chatQueueDelay: 125
    coreRateLimit:
      limit: 10
      reset: 1000 # in milliseconds
  # or without the optional ones:
  # - host: 'localhost'
  #   port: 25565
  #   serverName: 'Localhost'
  #   reconnectDelay: 2000
  #   chatQueueDelay: 125
