# Config file for ChomeNS Bot

prefixes:
  - 'default*'
  - 'defaultcbot '

commandSpyPrefixes:
  - '/defaultcbot '

consoleCommandPrefix: '.'

# how backup works is that it makes a http request for the address
# if the address is reachable it will not start the bot
# if the address is not reachable then it will start the bot

# *** it doesn't care about the status code

# if the bot has already been started and the address is back up it
# will stop the bot
backup:
  enabled: false
  address: 'https://fard.sex/check'
  interval: 1000 # in milliseconds
  failTimes: 2

database:
  enabled: false
  address: 'localhost' # jdbc:mariadb://<address>/chomens_bot
  username: 'chomens_bot'
  password: '123456'

chomeNSMod:
  enabled: false
  password: '123456' # secure password 2025
  players:
    - 'player username that has ChomeNS Mod'
    - 'Bob'
    - 'Jake'
    - 'Parker'

discord:
  enabled: false
  prefix: 'default!'
  token: 'token here'
  trustedRoleName: 'Trusted'
  adminRoleName: 'Admin'
  ownerRoleName: 'Owner'
  statusMessage: 'Say Gex'
  inviteLink: 'https://discord.gg/xdgCkUyaA4'
  servers:
    localhost:25565: 'channel id'

irc:
  enabled: false
  prefix: '!'
  host: 'irc.libera.chat'
  port: 6665
  name: 'chomens_bot'
  password: ''
  servers:
    localhost:25565: '#chomens/localhost' # channel name

music:
  urlRatelimit:
    seconds: 15
    limit: 7

colorPalette:
  primary: 'yellow'
  secondary: 'gold'
  defaultColor: 'gray' # ig java has the `default` keyword so i need to use defaultColor
  username: 'gold'
  uuid: 'aqua'
  string: 'aqua'
  number: 'gold'
  ownerName: 'green'

# you HAVE TO CHANGE THIS if you are hosting another instance of my bot.
ownerName: 'XxChange_mexX'

consoleChatFormat: '{"translate":"chat.type.text","with":["OWNER_NAME","MESSAGE"]}'

imposterFormatChecker:
  enabled: false
  key: ''

ownerAuthentication:
  enabled: false
  timeout: 10000 # 10 seconds - 10 * 1000

# if this is enabled when someone does a clear chat command the bot
# will tellraw `{player} cleared the chat`
announceClearChatUsername: false

trusted:
  - 'player name'

keys:
  trustedKey: 'trusted key here'
  adminKey: 'admin key here'
  ownerKey: 'owner key here'

weatherApiKey: 'key here' # weatherapi.com key

namespace: 'default_chomens_bot' # useful when you make a clone of the bot
teamName: 'default_chomens_bot' # i recommend having this value the same as namespace

core:
  # PLEASE give valid JSON component here
  customName: '[{"text":"ChomeNS ","color":"yellow"},{"text":"Core","color":"green"},{"text":"™","color":"gold"}]'

# https://code.chipmunk.land/ChomeNS/eval-server
eval:
  address: 'ws://localhost:3069'

selfCare:
  delay: 225 # NOTE: self care does NOT use chat queue

  # vanilla
  op: true
  gamemode: true
  endCredits: true

  # essentials
  vanish: true
  nickname: true
  socialspy: true
  mute: true

  # commandspy
  cspy: true

  # extras
  prefix:
    enabled: true
    prefix: '&8[&eChomeNS Bot&8]'

  username: true # MIGHT cause problem(s) if set to false (not tested,.,.)

bots:
  # username - optional, if not specified it will just use a random username
  # serverName - name it whatever you like, it will be used as server name in trusted broadcast and in console
  # hidden - if enabled, the server address will not show anywhere in the bot, including discord, netmsg, etc., except console
  # useCore - if enabled it just sends the command using chat instead of using core. recommended to enable useChat too when this is disabled
  # useCorePlaceBlock - uses the place block core instead of the main core. only used if useCore is enabled
  # useChat - when the bot tellraws it will chat instead of using the core to run tellraw
  # coreCommandSpy - set to true if server supports enabling player's commandspy though command block
  # resolveSRV - whether to resolve SRV records on the server. the notchian minecraft doesn't resolve them
  # essentialsMessages - the messages in essentials that the bot uses for self care (no example is intentional)
  # coreRateLimit - will ignore commands if reached the ratelimit

  - host: 'localhost'
    port: 25565
    serverName: 'Localhost'
    reconnectDelay: 2000
    chatQueueDelay: 125
  # or with the optional ones
  # - host: 'localhost'
  #   port: 25565
  #   username: 'ChomeNS_Bot'
  #   serverName: 'Localhost'
  #   hidden: false
  #   useCore: true
  #   useCorePlaceBlock: false
  #   useChat: false
  #   coreCommandSpy: false
  #   resolveSRV: true
  #   reconnectDelay: 2000
  #   chatQueueDelay: 125
  #   coreRateLimit:
  #     limit: 10
  #     reset: 1000 # in milliseconds
